_default:
    @just --list

# Basic認証用リクエスト
[group('command')]
basic user password url:
    curl -i -u '{{user}}:{{password}}' '{{url}}'

# フォーム認証用リクエスト
[group('command')]
form user password url:
    curl -i -L -c cookies.txt -b cookies.txt -d 'username={{user}}' -d 'password={{password}}' '{{url}}'