_default:
    @just --list

# Basic認証用リクエスト
[group('basic')]
basic user password url:
    curl -i -u '{{user}}:{{password}}' '{{url}}'

# フォーム認証用リクエスト
[group('form')]
form user password url:
    curl -i -X POST -d 'username={{user}}' -d 'password={{password}}' '{{url}}'